# Generated by Django 3.1.7 on 2021-03-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events_app.eventusers')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('status', models.CharField(choices=[('S', 'Single'), ('IR', 'In a Relationship'), ('M', 'Married'), ('W', 'Widowed')], max_length=2)),
                ('occupation', models.CharField(choices=[('S', 'Student'), ('NAN', 'Invalid'), ('W', 'Worker'), ('E', 'Entrepreneur')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events_app.eventusers')),
                ('goal_1', models.CharField(max_length=200)),
                ('goal_2', models.CharField(max_length=200)),
                ('goal_3', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=600)),
            ],
        ),
    ]
