# Generated by Django 3.1.7 on 2021-03-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_events_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(upload_to='event_images'),
        ),
    ]
