# Generated by Django 3.1.7 on 2021-03-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_auto_20210324_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(choices=[('SCOT', 'Scotland'), ('ENGL', 'ENGLAND'), ('WALE', 'WALES'), ('IREL', 'IRELAND')], max_length=4),
        ),
    ]
